// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MPI.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MPI.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* Mensaje_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Mensaje_reflection_ = NULL;
struct MensajeOneofInstance {
  const ::DiffieParams* dprms_;
  const ::DiffiePunto* dpt_;
  const ::MSJSesion* msgsn_;
  const ::MSJDialogo* msgd_;
}* Mensaje_default_oneof_instance_ = NULL;
const ::google::protobuf::Descriptor* DiffieParams_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DiffieParams_reflection_ = NULL;
const ::google::protobuf::Descriptor* DiffiePunto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DiffiePunto_reflection_ = NULL;
const ::google::protobuf::Descriptor* MSJSesion_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSJSesion_reflection_ = NULL;
const ::google::protobuf::Descriptor* MSJDialogo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSJDialogo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MPI_2eproto() {
  protobuf_AddDesc_MPI_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MPI.proto");
  GOOGLE_CHECK(file != NULL);
  Mensaje_descriptor_ = file->message_type(0);
  static const int Mensaje_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mensaje, msg_id_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Mensaje_default_oneof_instance_, dprms_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Mensaje_default_oneof_instance_, dpt_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Mensaje_default_oneof_instance_, msgsn_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Mensaje_default_oneof_instance_, msgd_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mensaje, msjsControl_),
  };
  Mensaje_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Mensaje_descriptor_,
      Mensaje::default_instance_,
      Mensaje_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mensaje, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mensaje, _unknown_fields_),
      -1,
      Mensaje_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mensaje, _oneof_case_[0]),
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Mensaje));
  DiffieParams_descriptor_ = file->message_type(1);
  static const int DiffieParams_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffieParams, p_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffieParams, a_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffieParams, b_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffieParams, g_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffieParams, g_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffieParams, n_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffieParams, h_),
  };
  DiffieParams_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DiffieParams_descriptor_,
      DiffieParams::default_instance_,
      DiffieParams_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffieParams, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffieParams, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DiffieParams));
  DiffiePunto_descriptor_ = file->message_type(2);
  static const int DiffiePunto_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffiePunto, x_val_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffiePunto, y_val_),
  };
  DiffiePunto_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DiffiePunto_descriptor_,
      DiffiePunto::default_instance_,
      DiffiePunto_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffiePunto, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DiffiePunto, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DiffiePunto));
  MSJSesion_descriptor_ = file->message_type(3);
  static const int MSJSesion_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSJSesion, idevento_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSJSesion, usuario_),
  };
  MSJSesion_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MSJSesion_descriptor_,
      MSJSesion::default_instance_,
      MSJSesion_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSJSesion, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSJSesion, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MSJSesion));
  MSJDialogo_descriptor_ = file->message_type(4);
  static const int MSJDialogo_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSJDialogo, msg_),
  };
  MSJDialogo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MSJDialogo_descriptor_,
      MSJDialogo::default_instance_,
      MSJDialogo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSJDialogo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSJDialogo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MSJDialogo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MPI_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Mensaje_descriptor_, &Mensaje::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DiffieParams_descriptor_, &DiffieParams::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DiffiePunto_descriptor_, &DiffiePunto::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MSJSesion_descriptor_, &MSJSesion::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MSJDialogo_descriptor_, &MSJDialogo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MPI_2eproto() {
  delete Mensaje::default_instance_;
  delete Mensaje_default_oneof_instance_;
  delete Mensaje_reflection_;
  delete DiffieParams::default_instance_;
  delete DiffieParams_reflection_;
  delete DiffiePunto::default_instance_;
  delete DiffiePunto_reflection_;
  delete MSJSesion::default_instance_;
  delete MSJSesion_reflection_;
  delete MSJDialogo::default_instance_;
  delete MSJDialogo_reflection_;
}

void protobuf_AddDesc_MPI_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tMPI.proto\"\237\001\n\007Mensaje\022\016\n\006msg_id\030\001 \002(\005\022"
    "\036\n\005dprms\030\002 \001(\0132\r.DiffieParamsH\000\022\033\n\003dpt\030\003"
    " \001(\0132\014.DiffiePuntoH\000\022\033\n\005msgsn\030\004 \001(\0132\n.MS"
    "JSesionH\000\022\033\n\004msgd\030\005 \001(\0132\013.MSJDialogoH\000B\r"
    "\n\013msjsControl\"_\n\014DiffieParams\022\t\n\001p\030\001 \002(\005"
    "\022\t\n\001a\030\002 \002(\005\022\t\n\001b\030\003 \002(\005\022\013\n\003G_x\030\004 \002(\005\022\013\n\003G"
    "_y\030\005 \002(\005\022\t\n\001n\030\006 \002(\005\022\t\n\001h\030\007 \002(\005\"+\n\013Diffie"
    "Punto\022\r\n\005x_val\030\001 \002(\005\022\r\n\005y_val\030\002 \002(\005\".\n\tM"
    "SJSesion\022\020\n\010idEvento\030\001 \002(\005\022\017\n\007usuario\030\002 "
    "\001(\t\"\031\n\nMSJDialogo\022\013\n\003msg\030\001 \002(\t", 390);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MPI.proto", &protobuf_RegisterTypes);
  Mensaje::default_instance_ = new Mensaje();
  Mensaje_default_oneof_instance_ = new MensajeOneofInstance;
  DiffieParams::default_instance_ = new DiffieParams();
  DiffiePunto::default_instance_ = new DiffiePunto();
  MSJSesion::default_instance_ = new MSJSesion();
  MSJDialogo::default_instance_ = new MSJDialogo();
  Mensaje::default_instance_->InitAsDefaultInstance();
  DiffieParams::default_instance_->InitAsDefaultInstance();
  DiffiePunto::default_instance_->InitAsDefaultInstance();
  MSJSesion::default_instance_->InitAsDefaultInstance();
  MSJDialogo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MPI_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MPI_2eproto {
  StaticDescriptorInitializer_MPI_2eproto() {
    protobuf_AddDesc_MPI_2eproto();
  }
} static_descriptor_initializer_MPI_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Mensaje::kMsgIdFieldNumber;
const int Mensaje::kDprmsFieldNumber;
const int Mensaje::kDptFieldNumber;
const int Mensaje::kMsgsnFieldNumber;
const int Mensaje::kMsgdFieldNumber;
#endif  // !_MSC_VER

Mensaje::Mensaje()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Mensaje)
}

void Mensaje::InitAsDefaultInstance() {
  Mensaje_default_oneof_instance_->dprms_ = const_cast< ::DiffieParams*>(&::DiffieParams::default_instance());
  Mensaje_default_oneof_instance_->dpt_ = const_cast< ::DiffiePunto*>(&::DiffiePunto::default_instance());
  Mensaje_default_oneof_instance_->msgsn_ = const_cast< ::MSJSesion*>(&::MSJSesion::default_instance());
  Mensaje_default_oneof_instance_->msgd_ = const_cast< ::MSJDialogo*>(&::MSJDialogo::default_instance());
}

Mensaje::Mensaje(const Mensaje& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Mensaje)
}

void Mensaje::SharedCtor() {
  _cached_size_ = 0;
  msg_id_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  clear_has_msjsControl();
}

Mensaje::~Mensaje() {
  // @@protoc_insertion_point(destructor:Mensaje)
  SharedDtor();
}

void Mensaje::SharedDtor() {
  if (has_msjsControl()) {
    clear_msjsControl();
  }
  if (this != default_instance_) {
  }
}

void Mensaje::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Mensaje::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Mensaje_descriptor_;
}

const Mensaje& Mensaje::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MPI_2eproto();
  return *default_instance_;
}

Mensaje* Mensaje::default_instance_ = NULL;

Mensaje* Mensaje::New() const {
  return new Mensaje;
}

void Mensaje::clear_msjsControl() {
  switch(msjsControl_case()) {
    case kDprms: {
      delete msjsControl_.dprms_;
      break;
    }
    case kDpt: {
      delete msjsControl_.dpt_;
      break;
    }
    case kMsgsn: {
      delete msjsControl_.msgsn_;
      break;
    }
    case kMsgd: {
      delete msjsControl_.msgd_;
      break;
    }
    case MSJSCONTROL_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = MSJSCONTROL_NOT_SET;
}


void Mensaje::Clear() {
  msg_id_ = 0;
  clear_msjsControl();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Mensaje::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Mensaje)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 msg_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &msg_id_)));
          set_has_msg_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_dprms;
        break;
      }

      // optional .DiffieParams dprms = 2;
      case 2: {
        if (tag == 18) {
         parse_dprms:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dprms()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_dpt;
        break;
      }

      // optional .DiffiePunto dpt = 3;
      case 3: {
        if (tag == 26) {
         parse_dpt:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dpt()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_msgsn;
        break;
      }

      // optional .MSJSesion msgsn = 4;
      case 4: {
        if (tag == 34) {
         parse_msgsn:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_msgsn()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_msgd;
        break;
      }

      // optional .MSJDialogo msgd = 5;
      case 5: {
        if (tag == 42) {
         parse_msgd:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_msgd()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Mensaje)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Mensaje)
  return false;
#undef DO_
}

void Mensaje::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Mensaje)
  // required int32 msg_id = 1;
  if (has_msg_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->msg_id(), output);
  }

  // optional .DiffieParams dprms = 2;
  if (has_dprms()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->dprms(), output);
  }

  // optional .DiffiePunto dpt = 3;
  if (has_dpt()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->dpt(), output);
  }

  // optional .MSJSesion msgsn = 4;
  if (has_msgsn()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->msgsn(), output);
  }

  // optional .MSJDialogo msgd = 5;
  if (has_msgd()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->msgd(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Mensaje)
}

::google::protobuf::uint8* Mensaje::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Mensaje)
  // required int32 msg_id = 1;
  if (has_msg_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->msg_id(), target);
  }

  // optional .DiffieParams dprms = 2;
  if (has_dprms()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->dprms(), target);
  }

  // optional .DiffiePunto dpt = 3;
  if (has_dpt()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->dpt(), target);
  }

  // optional .MSJSesion msgsn = 4;
  if (has_msgsn()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->msgsn(), target);
  }

  // optional .MSJDialogo msgd = 5;
  if (has_msgd()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->msgd(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Mensaje)
  return target;
}

int Mensaje::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 msg_id = 1;
    if (has_msg_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->msg_id());
    }

  }
  switch (msjsControl_case()) {
    // optional .DiffieParams dprms = 2;
    case kDprms: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->dprms());
      break;
    }
    // optional .DiffiePunto dpt = 3;
    case kDpt: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->dpt());
      break;
    }
    // optional .MSJSesion msgsn = 4;
    case kMsgsn: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->msgsn());
      break;
    }
    // optional .MSJDialogo msgd = 5;
    case kMsgd: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->msgd());
      break;
    }
    case MSJSCONTROL_NOT_SET: {
      break;
    }
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Mensaje::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Mensaje* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Mensaje*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Mensaje::MergeFrom(const Mensaje& from) {
  GOOGLE_CHECK_NE(&from, this);
  switch (from.msjsControl_case()) {
    case kDprms: {
      mutable_dprms()->::DiffieParams::MergeFrom(from.dprms());
      break;
    }
    case kDpt: {
      mutable_dpt()->::DiffiePunto::MergeFrom(from.dpt());
      break;
    }
    case kMsgsn: {
      mutable_msgsn()->::MSJSesion::MergeFrom(from.msgsn());
      break;
    }
    case kMsgd: {
      mutable_msgd()->::MSJDialogo::MergeFrom(from.msgd());
      break;
    }
    case MSJSCONTROL_NOT_SET: {
      break;
    }
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msg_id()) {
      set_msg_id(from.msg_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Mensaje::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Mensaje::CopyFrom(const Mensaje& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Mensaje::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_dprms()) {
    if (!this->dprms().IsInitialized()) return false;
  }
  if (has_dpt()) {
    if (!this->dpt().IsInitialized()) return false;
  }
  if (has_msgsn()) {
    if (!this->msgsn().IsInitialized()) return false;
  }
  if (has_msgd()) {
    if (!this->msgd().IsInitialized()) return false;
  }
  return true;
}

void Mensaje::Swap(Mensaje* other) {
  if (other != this) {
    std::swap(msg_id_, other->msg_id_);
    std::swap(msjsControl_, other->msjsControl_);
    std::swap(_oneof_case_[0], other->_oneof_case_[0]);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Mensaje::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Mensaje_descriptor_;
  metadata.reflection = Mensaje_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int DiffieParams::kPFieldNumber;
const int DiffieParams::kAFieldNumber;
const int DiffieParams::kBFieldNumber;
const int DiffieParams::kGXFieldNumber;
const int DiffieParams::kGYFieldNumber;
const int DiffieParams::kNFieldNumber;
const int DiffieParams::kHFieldNumber;
#endif  // !_MSC_VER

DiffieParams::DiffieParams()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DiffieParams)
}

void DiffieParams::InitAsDefaultInstance() {
}

DiffieParams::DiffieParams(const DiffieParams& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DiffieParams)
}

void DiffieParams::SharedCtor() {
  _cached_size_ = 0;
  p_ = 0;
  a_ = 0;
  b_ = 0;
  g_x_ = 0;
  g_y_ = 0;
  n_ = 0;
  h_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DiffieParams::~DiffieParams() {
  // @@protoc_insertion_point(destructor:DiffieParams)
  SharedDtor();
}

void DiffieParams::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DiffieParams::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DiffieParams::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DiffieParams_descriptor_;
}

const DiffieParams& DiffieParams::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MPI_2eproto();
  return *default_instance_;
}

DiffieParams* DiffieParams::default_instance_ = NULL;

DiffieParams* DiffieParams::New() const {
  return new DiffieParams;
}

void DiffieParams::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<DiffieParams*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 127) {
    ZR_(p_, h_);
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DiffieParams::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DiffieParams)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 p = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &p_)));
          set_has_p();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_a;
        break;
      }

      // required int32 a = 2;
      case 2: {
        if (tag == 16) {
         parse_a:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &a_)));
          set_has_a();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_b;
        break;
      }

      // required int32 b = 3;
      case 3: {
        if (tag == 24) {
         parse_b:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &b_)));
          set_has_b();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_G_x;
        break;
      }

      // required int32 G_x = 4;
      case 4: {
        if (tag == 32) {
         parse_G_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &g_x_)));
          set_has_g_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_G_y;
        break;
      }

      // required int32 G_y = 5;
      case 5: {
        if (tag == 40) {
         parse_G_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &g_y_)));
          set_has_g_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_n;
        break;
      }

      // required int32 n = 6;
      case 6: {
        if (tag == 48) {
         parse_n:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &n_)));
          set_has_n();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_h;
        break;
      }

      // required int32 h = 7;
      case 7: {
        if (tag == 56) {
         parse_h:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &h_)));
          set_has_h();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DiffieParams)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DiffieParams)
  return false;
#undef DO_
}

void DiffieParams::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DiffieParams)
  // required int32 p = 1;
  if (has_p()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->p(), output);
  }

  // required int32 a = 2;
  if (has_a()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->a(), output);
  }

  // required int32 b = 3;
  if (has_b()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->b(), output);
  }

  // required int32 G_x = 4;
  if (has_g_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->g_x(), output);
  }

  // required int32 G_y = 5;
  if (has_g_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->g_y(), output);
  }

  // required int32 n = 6;
  if (has_n()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->n(), output);
  }

  // required int32 h = 7;
  if (has_h()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->h(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:DiffieParams)
}

::google::protobuf::uint8* DiffieParams::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DiffieParams)
  // required int32 p = 1;
  if (has_p()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->p(), target);
  }

  // required int32 a = 2;
  if (has_a()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->a(), target);
  }

  // required int32 b = 3;
  if (has_b()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->b(), target);
  }

  // required int32 G_x = 4;
  if (has_g_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->g_x(), target);
  }

  // required int32 G_y = 5;
  if (has_g_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->g_y(), target);
  }

  // required int32 n = 6;
  if (has_n()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->n(), target);
  }

  // required int32 h = 7;
  if (has_h()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->h(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DiffieParams)
  return target;
}

int DiffieParams::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 p = 1;
    if (has_p()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->p());
    }

    // required int32 a = 2;
    if (has_a()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->a());
    }

    // required int32 b = 3;
    if (has_b()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->b());
    }

    // required int32 G_x = 4;
    if (has_g_x()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->g_x());
    }

    // required int32 G_y = 5;
    if (has_g_y()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->g_y());
    }

    // required int32 n = 6;
    if (has_n()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->n());
    }

    // required int32 h = 7;
    if (has_h()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->h());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DiffieParams::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DiffieParams* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DiffieParams*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DiffieParams::MergeFrom(const DiffieParams& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_p()) {
      set_p(from.p());
    }
    if (from.has_a()) {
      set_a(from.a());
    }
    if (from.has_b()) {
      set_b(from.b());
    }
    if (from.has_g_x()) {
      set_g_x(from.g_x());
    }
    if (from.has_g_y()) {
      set_g_y(from.g_y());
    }
    if (from.has_n()) {
      set_n(from.n());
    }
    if (from.has_h()) {
      set_h(from.h());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DiffieParams::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DiffieParams::CopyFrom(const DiffieParams& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DiffieParams::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000007f) != 0x0000007f) return false;

  return true;
}

void DiffieParams::Swap(DiffieParams* other) {
  if (other != this) {
    std::swap(p_, other->p_);
    std::swap(a_, other->a_);
    std::swap(b_, other->b_);
    std::swap(g_x_, other->g_x_);
    std::swap(g_y_, other->g_y_);
    std::swap(n_, other->n_);
    std::swap(h_, other->h_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DiffieParams::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DiffieParams_descriptor_;
  metadata.reflection = DiffieParams_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int DiffiePunto::kXValFieldNumber;
const int DiffiePunto::kYValFieldNumber;
#endif  // !_MSC_VER

DiffiePunto::DiffiePunto()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DiffiePunto)
}

void DiffiePunto::InitAsDefaultInstance() {
}

DiffiePunto::DiffiePunto(const DiffiePunto& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DiffiePunto)
}

void DiffiePunto::SharedCtor() {
  _cached_size_ = 0;
  x_val_ = 0;
  y_val_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DiffiePunto::~DiffiePunto() {
  // @@protoc_insertion_point(destructor:DiffiePunto)
  SharedDtor();
}

void DiffiePunto::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DiffiePunto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DiffiePunto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DiffiePunto_descriptor_;
}

const DiffiePunto& DiffiePunto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MPI_2eproto();
  return *default_instance_;
}

DiffiePunto* DiffiePunto::default_instance_ = NULL;

DiffiePunto* DiffiePunto::New() const {
  return new DiffiePunto;
}

void DiffiePunto::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<DiffiePunto*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(x_val_, y_val_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DiffiePunto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DiffiePunto)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 x_val = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &x_val_)));
          set_has_x_val();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_y_val;
        break;
      }

      // required int32 y_val = 2;
      case 2: {
        if (tag == 16) {
         parse_y_val:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &y_val_)));
          set_has_y_val();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DiffiePunto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DiffiePunto)
  return false;
#undef DO_
}

void DiffiePunto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DiffiePunto)
  // required int32 x_val = 1;
  if (has_x_val()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->x_val(), output);
  }

  // required int32 y_val = 2;
  if (has_y_val()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->y_val(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:DiffiePunto)
}

::google::protobuf::uint8* DiffiePunto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DiffiePunto)
  // required int32 x_val = 1;
  if (has_x_val()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->x_val(), target);
  }

  // required int32 y_val = 2;
  if (has_y_val()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->y_val(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DiffiePunto)
  return target;
}

int DiffiePunto::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 x_val = 1;
    if (has_x_val()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->x_val());
    }

    // required int32 y_val = 2;
    if (has_y_val()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->y_val());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DiffiePunto::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DiffiePunto* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DiffiePunto*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DiffiePunto::MergeFrom(const DiffiePunto& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_x_val()) {
      set_x_val(from.x_val());
    }
    if (from.has_y_val()) {
      set_y_val(from.y_val());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DiffiePunto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DiffiePunto::CopyFrom(const DiffiePunto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DiffiePunto::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void DiffiePunto::Swap(DiffiePunto* other) {
  if (other != this) {
    std::swap(x_val_, other->x_val_);
    std::swap(y_val_, other->y_val_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DiffiePunto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DiffiePunto_descriptor_;
  metadata.reflection = DiffiePunto_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MSJSesion::kIdEventoFieldNumber;
const int MSJSesion::kUsuarioFieldNumber;
#endif  // !_MSC_VER

MSJSesion::MSJSesion()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MSJSesion)
}

void MSJSesion::InitAsDefaultInstance() {
}

MSJSesion::MSJSesion(const MSJSesion& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MSJSesion)
}

void MSJSesion::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  idevento_ = 0;
  usuario_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MSJSesion::~MSJSesion() {
  // @@protoc_insertion_point(destructor:MSJSesion)
  SharedDtor();
}

void MSJSesion::SharedDtor() {
  if (usuario_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete usuario_;
  }
  if (this != default_instance_) {
  }
}

void MSJSesion::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSJSesion::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSJSesion_descriptor_;
}

const MSJSesion& MSJSesion::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MPI_2eproto();
  return *default_instance_;
}

MSJSesion* MSJSesion::default_instance_ = NULL;

MSJSesion* MSJSesion::New() const {
  return new MSJSesion;
}

void MSJSesion::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    idevento_ = 0;
    if (has_usuario()) {
      if (usuario_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        usuario_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MSJSesion::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MSJSesion)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 idEvento = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &idevento_)));
          set_has_idevento();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_usuario;
        break;
      }

      // optional string usuario = 2;
      case 2: {
        if (tag == 18) {
         parse_usuario:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_usuario()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->usuario().data(), this->usuario().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "usuario");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MSJSesion)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MSJSesion)
  return false;
#undef DO_
}

void MSJSesion::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MSJSesion)
  // required int32 idEvento = 1;
  if (has_idevento()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->idevento(), output);
  }

  // optional string usuario = 2;
  if (has_usuario()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->usuario().data(), this->usuario().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "usuario");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->usuario(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MSJSesion)
}

::google::protobuf::uint8* MSJSesion::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MSJSesion)
  // required int32 idEvento = 1;
  if (has_idevento()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->idevento(), target);
  }

  // optional string usuario = 2;
  if (has_usuario()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->usuario().data(), this->usuario().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "usuario");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->usuario(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MSJSesion)
  return target;
}

int MSJSesion::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 idEvento = 1;
    if (has_idevento()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->idevento());
    }

    // optional string usuario = 2;
    if (has_usuario()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->usuario());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSJSesion::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MSJSesion* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MSJSesion*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MSJSesion::MergeFrom(const MSJSesion& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_idevento()) {
      set_idevento(from.idevento());
    }
    if (from.has_usuario()) {
      set_usuario(from.usuario());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MSJSesion::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSJSesion::CopyFrom(const MSJSesion& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSJSesion::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MSJSesion::Swap(MSJSesion* other) {
  if (other != this) {
    std::swap(idevento_, other->idevento_);
    std::swap(usuario_, other->usuario_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MSJSesion::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSJSesion_descriptor_;
  metadata.reflection = MSJSesion_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MSJDialogo::kMsgFieldNumber;
#endif  // !_MSC_VER

MSJDialogo::MSJDialogo()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MSJDialogo)
}

void MSJDialogo::InitAsDefaultInstance() {
}

MSJDialogo::MSJDialogo(const MSJDialogo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MSJDialogo)
}

void MSJDialogo::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MSJDialogo::~MSJDialogo() {
  // @@protoc_insertion_point(destructor:MSJDialogo)
  SharedDtor();
}

void MSJDialogo::SharedDtor() {
  if (msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete msg_;
  }
  if (this != default_instance_) {
  }
}

void MSJDialogo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSJDialogo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSJDialogo_descriptor_;
}

const MSJDialogo& MSJDialogo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MPI_2eproto();
  return *default_instance_;
}

MSJDialogo* MSJDialogo::default_instance_ = NULL;

MSJDialogo* MSJDialogo::New() const {
  return new MSJDialogo;
}

void MSJDialogo::Clear() {
  if (has_msg()) {
    if (msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
      msg_->clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MSJDialogo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MSJDialogo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string msg = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->msg().data(), this->msg().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "msg");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MSJDialogo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MSJDialogo)
  return false;
#undef DO_
}

void MSJDialogo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MSJDialogo)
  // required string msg = 1;
  if (has_msg()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msg().data(), this->msg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->msg(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MSJDialogo)
}

::google::protobuf::uint8* MSJDialogo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MSJDialogo)
  // required string msg = 1;
  if (has_msg()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msg().data(), this->msg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->msg(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MSJDialogo)
  return target;
}

int MSJDialogo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string msg = 1;
    if (has_msg()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->msg());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSJDialogo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MSJDialogo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MSJDialogo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MSJDialogo::MergeFrom(const MSJDialogo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msg()) {
      set_msg(from.msg());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MSJDialogo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSJDialogo::CopyFrom(const MSJDialogo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSJDialogo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MSJDialogo::Swap(MSJDialogo* other) {
  if (other != this) {
    std::swap(msg_, other->msg_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MSJDialogo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSJDialogo_descriptor_;
  metadata.reflection = MSJDialogo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
